挂载持久化卷时，可以提前创建好对应目录，这样可以不依赖docker的自动创建目录的特性，避免权限问题
huan/docker-wechat pull request #203
Opened 2023-07-20 04:03 UTC by etoyz

[#165 ](https://github.com/huan/docker-wechat/issues/165#issuecomment-1643063633)

2023-07-20 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/huan/docker-wechat?pullRequest=203) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/huan/docker-wechat?pullRequest=203) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/huan/docker-wechat?pullRequest=203) it.</sub>

2023-10-23 21:12 UTC, huan approved these changes
LGTM

2023-10-23 21:24 UTC, huan requested changes
Please fix the shellcheck warnings.

2023-10-23 21:28 UTC, huan commented on dochat.sh
> +  mkdir $HOME/DoChat/"WeChat Files"/ -p
And it would be great to have a variable `$HOST_DIR_HOME_DOCHAT_WECHAT_FILES` to hold the entire string and reference it in the code `-v "$HOST_DIR_HOME_DOCHAT_WECHAT_FILES" ...` later:

```diff
+   HOST_DIR_HOME_DOCHAT_WECHAT_FILES = "$HOME/DoChat/WeChat Files/"
-   mkdir $HOME/DoChat/"WeChat Files"/ -p
+   mkdir "$HOST_DIR_HOME_DOCHAT_WECHAT_FILES" -p
```

2023-10-24 03:21 UTC, etoyz reviewed
已修改

2023-10-24 03:23 UTC, etoyz reviewed
已修改

2023-10-24 03:24 UTC, huan requested changes

2023-10-24 03:24 UTC, huan commented on dochat.sh
> +  mkdir "$HOME"/DoChat/"Applcation Data"/
We should use `HOST_DIR_HOME_DOCHAT_APPLICATION_DATA` here, too.

2023-10-24 03:24 UTC, huan commented on dochat.sh
>      -v "$HOME/DoChat/WeChat Files/":'/home/user/WeChat Files/' \
Use `HOST_DIR_HOME_DOCHAT_WECHAT_FILES` in this line to ensure consistency.

2023-10-24 03:24 UTC, huan commented on dochat.sh
> +    -v "$HOME/DoChat/Applcation Data/":'/home/user/.wine/drive_c/users/user/Application Data/' \
Use `HOST_DIR_HOME_DOCHAT_APPLICATION_DATA` in this line to ensure consistency.

2023-10-24 04:12 UTC, huan approved these changes
LGTM

2023-10-24 04:13 UTC, huan commented
Thank you very much for the improvements!

2023-10-24 04:16 UTC, huan commented
Can you fix the failure in the CI?

After the CI passed this PR will be ready to be merged.

2023-10-24 06:00 UTC, etoyz commented
不好意思，我不太熟悉CI（： @huan

2023-10-24 09:21 UTC, huan approved these changes
LGTM

2023-10-24 09:21 UTC, merged