Disallow root script run
huan/docker-wechat pull request #209
Opened 2023-10-22 16:37 UTC by DE0CH

I added a check to stop the script if the user is root. Also, I hid an environment variable `ALLOWROOT` which if set to 1 will allow the script to run if the user wants to run it as root for whatever reason. 

This would avoid numerous issues with `~/DoChat` becoming owned by root causing permission denided issues (such as in https://github.com/huan/docker-wechat/issues/165 and  https://github.com/huan/docker-wechat/issues/178). 

Also, I got rid of the warning message of `lshw -C display` which, if not run with sudo, confusingly prints out `WARNING: you should run this program as super-user.`, which can mislead people (including me) to run the script with sudo

2023-10-22 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/huan/docker-wechat?pullRequest=209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/huan/docker-wechat?pullRequest=209) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/huan/docker-wechat?pullRequest=209) it.</sub>

2023-10-22 16:58 UTC, huan requested changes
Thanks for great improvement, it definitely can help users to prevent the related issues you mentioned.

it will good to be merged after you added the message I mentioned in the comment.

2023-10-22 16:58 UTC, huan commented on dochat.sh
> +then echo "Please do not run this script as root."
Can you add another message to show a link to this pull request so that the user can get more context about the root issue?

2023-10-22 17:35 UTC, DE0CH commented
Thanks. I just made the changes requested.

2023-10-22 21:38 UTC, huan submitted a review, later dismissed
LGTM

2023-10-22 21:42 UTC, huan approved these changes
Fixed shellcheck

2023-10-22 21:42 UTC, merged

2023-10-22 21:46 UTC, huan commented
It seems that there's problem when publishing the image to docker hub: https://github.com/huan/docker-wechat/actions/runs/6606361107/job/17942485588#step:5:294

@DE0CH Could you please take a look at it?

Thank you very much!

2023-10-23 07:24 UTC, DE0CH commented
Yep. https://github.com/huan/docker-wechat/pull/210.

I actually ran into this problem when debugging, but seeing that the docker image somehow was built and published to the docker hub I thought it didn't need fixing.